// Code generated by protoc-gen-go.
// source: deis.proto
// DO NOT EDIT!

/*
Package _proto is a generated protocol buffer package.

It is generated from these files:
	deis.proto

It has these top-level messages:
	Request
	Response
*/
package _proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Response struct {
	Message string `protobuf:"bytes,1,opt,name=Message" json:"Message,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*Request)(nil), "_proto.Request")
	proto.RegisterType((*Response)(nil), "_proto.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for PoweredBy service

type PoweredByClient interface {
	PoweredBy(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type poweredByClient struct {
	cc *grpc.ClientConn
}

func NewPoweredByClient(cc *grpc.ClientConn) PoweredByClient {
	return &poweredByClient{cc}
}

func (c *poweredByClient) PoweredBy(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/_proto.PoweredBy/PoweredBy", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PoweredBy service

type PoweredByServer interface {
	PoweredBy(context.Context, *Request) (*Response, error)
}

func RegisterPoweredByServer(s *grpc.Server, srv PoweredByServer) {
	s.RegisterService(&_PoweredBy_serviceDesc, srv)
}

func _PoweredBy_PoweredBy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoweredByServer).PoweredBy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/_proto.PoweredBy/PoweredBy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoweredByServer).PoweredBy(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _PoweredBy_serviceDesc = grpc.ServiceDesc{
	ServiceName: "_proto.PoweredBy",
	HandlerType: (*PoweredByServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PoweredBy",
			Handler:    _PoweredBy_PoweredBy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("deis.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 131 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x49, 0xcd, 0x2c,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x8b, 0x07, 0xd3, 0x4a, 0xb2, 0x5c, 0xec, 0x41,
	0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c,
	0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x92, 0x0a, 0x17, 0x47, 0x50, 0x6a, 0x71, 0x41, 0x7e,
	0x5e, 0x71, 0xaa, 0x90, 0x04, 0x17, 0xbb, 0x6f, 0x6a, 0x71, 0x71, 0x62, 0x3a, 0x4c, 0x09, 0x8c,
	0x6b, 0x64, 0xcb, 0xc5, 0x19, 0x90, 0x5f, 0x9e, 0x5a, 0x94, 0x9a, 0xe2, 0x54, 0x29, 0x64, 0x80,
	0xcc, 0xe1, 0xd7, 0x83, 0xd8, 0xa3, 0x07, 0xb5, 0x44, 0x4a, 0x00, 0x21, 0x00, 0x31, 0x56, 0x89,
	0x21, 0x89, 0x0d, 0x2c, 0x62, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x4c, 0x1a, 0xc7, 0xa2, 0xa0,
	0x00, 0x00, 0x00,
}
